// Branded letterhead shell that wraps a generated document's rendered HTML.
//
// Used by the print route (manager "Save as PDF") and the tenant-facing view.
// Header: FindStoop wordmark + property address. Footer: provenance line, the
// Equal Housing Opportunity mark, and the "not legal advice" disclaimer that
// every generated document must carry.

import EhoMark from './EhoMark'

interface LetterheadProps {
  // Right-aligned reference shown in the header (e.g. document title or id).
  reference?: string
  // Property line shown under the logo.
  propertyAddress?: string
  // The rendered inner HTML of the letter (from a template's render()).
  bodyHtml: string
}

export default function Letterhead({ reference, propertyAddress, bodyHtml }: LetterheadProps) {
  return (
    <div className="doc-letterhead bg-white text-ink">
      {/* Header */}
      <div className="flex items-start justify-between border-b border-gray-200 pb-4 mb-8">
        <div>
          <img src="/findstoop-logo.png" alt="FindStoop" className="h-9" />
          {propertyAddress && (
            <p className="text-xs text-mute mt-2 font-sans">{propertyAddress}</p>
          )}
        </div>
        {reference && (
          <p className="text-[11px] text-mute font-sans tracking-wider uppercase text-right max-w-[40%]">
            {reference}
          </p>
        )}
      </div>

      {/* Body — rendered template HTML */}
      <div
        className="doc-content"
        // Template output is produced by our own code with escaped user input.
        dangerouslySetInnerHTML={{ __html: bodyHtml }}
      />

      {/* Footer */}
      <div className="mt-12 pt-5 border-t border-gray-200 flex items-end justify-between gap-4 font-sans">
        <div className="text-[11px] text-mute leading-relaxed">
          <p>Generated by FindStoop · findstoop.com</p>
          <p className="italic mt-0.5">This document does not constitute legal advice.</p>
        </div>
        <EhoMark className="text-mute shrink-0" />
      </div>

      {/* Document body styling — serif legal-letter look, scoped to .doc-content.
          Travels with the component so it renders identically on the print
          route and the tenant view. */}
      <style>{`
        .doc-letterhead { font-family: Georgia, "Times New Roman", serif; line-height: 1.6; }
        .doc-content { font-size: 14px; }
        .doc-content .doc-date { color: #6E6E73; font-family: ui-sans-serif, system-ui, sans-serif; font-size: 12px; margin-bottom: 1.5rem; }
        .doc-content .doc-title { font-size: 24px; font-weight: 700; margin: 0 0 1rem; }
        .doc-content .doc-to { margin-bottom: 1.5rem; }
        .doc-content .doc-body p { margin: 0 0 0.9rem; }
        .doc-content .doc-h2 { font-size: 15px; font-weight: 700; margin: 1.4rem 0 0.5rem; }
        .doc-content .doc-list { margin: 0 0 1rem 1.2rem; list-style: disc; }
        .doc-content .doc-list li { margin-bottom: 0.35rem; }
        .doc-content .doc-terms { width: 100%; border-collapse: collapse; margin: 0.5rem 0 1.2rem; font-size: 13.5px; }
        .doc-content .doc-terms th { text-align: left; font-weight: 600; padding: 0.45rem 0; border-bottom: 1px solid #eee; width: 45%; }
        .doc-content .doc-terms td { text-align: right; padding: 0.45rem 0; border-bottom: 1px solid #eee; }
        .doc-content .doc-terms tr.doc-total th, .doc-content .doc-terms tr.doc-total td { font-weight: 700; border-top: 2px solid #ddd; }
        .doc-content .doc-statutory { background: #fbf7ee; border-left: 3px solid #c79a3a; padding: 0.75rem 1rem; font-weight: 600; }
        .doc-content .doc-signoff { margin-top: 1.6rem; }
        .doc-content .doc-sign-name { margin-top: 0.4rem; }
        .doc-content .doc-contact { color: #6E6E73; font-family: ui-sans-serif, system-ui, sans-serif; font-size: 12px; }
      `}</style>
    </div>
  )
}
